#!/bin/bash

file-size()
{
  wc -c "$1" | cut -d' ' -f1
}

has-enough-complexity()
{
  insize="$(file-size "$2")"
  outsize="$(file-size "$3")"
  return $(($1 == 0 && outsize >= insize * 97 / 100))
}

if [ "$#" -lt 2 ]
then
  echo "Usage: $0 INFILE MAX_ITER"
  exit 1
fi

cp "$1" "${1/./-0.}"

i=0
redo=0
echo "======== Iter $i"
while [ "$i" -lt "$2" ]
do
  j=$((i + 1))
  origfile="$1"
  infile="${1/./-$i.}"
  outfile="${1/./-$j.}"
  ./complex-glitch "$infile" "$outfile"
  if has-enough-complexity "$?" "$infile" "$outfile"
  then
    redo="$((redo + 1))"
    echo "-------- redo $redo"
    continue
  fi
  i="$j"
  redo=0
  echo "======== Iter $i"
done
