#!/usr/bin/env ruby

MIN_RANDOMNESS = 0
MAX_RANDOMNESS = 100000

def main(args)
  if args.length < 2
    fail 'Usage: glitch.rb INFILE RANDOMNESS >OUTFILE'
  end

  infile = args[0]
  randomness = args[1].to_i

  unless MIN_RANDOMNESS <= randomness and randomness <= MAX_RANDOMNESS
    fail "RANDOMNESS must be between #{MIN_RANDOMNESS} and #{MAX_RANDOMNESS}."
  end

  ignore_first_n_bytes = 32  # Do not break the header.
  File.open(args[0], mode='rb').each_byte do |byte|
    r = rand(MAX_RANDOMNESS)
    if 0 < ignore_first_n_bytes
      ignore_first_n_bytes -= 1
    else
      if r < randomness
        byte = rand(256)
      end
    end

    STDOUT.putc byte
  end
end

main(ARGV)
